### ISSUE TITLE
Fiters.multipleSelect did not work in second component tab at Salesforce LWC

### ISSUE THREAD

**Issue by good-ghost** [ghiscoding/slickgrid-universal#1443] opened 2024-03-27 03:42 UTC
### Describe the bug

When open the two tabs each has grid component which set the Fiters.multipleSelect. One component's filter did work, but the other grid component didn't.

### Reproduction

1. Create slickgridHelper component by recommended LWC procedure.
2. Create two grid components with helper and Filters.multipleSelect and place the component as each tab.
3. Open two tabs has grid component
4. One component fitter did work. but the other component filter did not work.

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | Salesforce |
| Slickgrid-Universal | 4.5.0 |
| TypeScript          | - |
| Browser(s)          | Chrome |
| System OS           | Windows 10 |
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment] 2024-03-27 04:30
there is not enough information to help in troubleshooting, I think the only thing that you need to make sure if that your `collection` is filled **before** you initialize the grid, because all filters are synchronous and expect data to be available before creating the grid.

**Comment by good-ghost** [comment] 2024-03-29 02:06
Here is re-produce step.
I used data.js (include json data) instead of @wire or other apex method for this sample.

- slickGridHelper.js
```
import slickGrid_bundle from '@salesforce/resourceUrl/SlickGrid';
import { loadStyle, loadScript } from 'lightning/platformResourceLoader';

// declare variables for all types, this will allow us to use `Formatters.bold` instead of `Slicker.Formatters.bold`
// all Wikis are written without the `Slicker` namespace, so doing this approach is better
export const Aggregators = {};
export const BindingService = {};
export const Editors = {};
export const Enums = {};
export const Filters = {};
export const Formatters = {};
export const GroupTotalFormatters = {};
export const SortComparers = {};
export const Utilities = {};
export const GridBundle = {};
export const SlickGlobalEditorLock = {}; // for 4.x only

/** Load all necessary SlickGrid resources (css/scripts) */
export async function loadResources(component) {
    await loadStyle(component, `${slickGrid_bundle}/styles/css/slickgrid-theme-salesforce.css`);
    await loadScript(component, `${slickGrid_bundle}/slickgrid-vanilla-bundle.js`);

    Aggregators = Slicker.Aggregators;
    BindingService = Slicker.BindingService;
    Editors = Slicker.Editors;
    Enums = Slicker.Enums;
    Filters = Slicker.Filters;
    Formatters = Slicker.Formatters;
    GroupTotalFormatters = Slicker.GroupTotalFormatters;
    SortComparers = Slicker.SortComparers;
    Utilities = Slicker.Utilities;
    GridBundle = Slicker.GridBundle;
    SlickGlobalEditorLock = Slicker.SlickGlobalEditorLock; // for 4.x only

    console.log('load slickgrid script');
}
```

- grid1.html
```
<template>
    <div class="main">
        <!-- show a spinner -->
        <div if:false={isLoaded} class="slds-is-relative">
            <lightning-spinner alternative-text="Loading...">
            </lightning-spinner>
        </div>

        <!-- slickGrid container-->
        <div class="grid-container slds-var-p-horizontal_small">
            <div lwc:dom="manual" class="user-grid"></div>
        </div>
    </div>
</template>
```

- grid1.js
```
import { LightningElement, api, wire } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';

import { Editors, Enums, Filters, Formatters, GridBundle, loadResources } from 'c/slickGridHelper';

// sample data
import { customers } from './data';

// // Apex Class.method
// import getSomeData from '@salesforce/apex/SomeService.getSomeData';

const columns = [
	{
		id: 'name', name: 'Name', field: 'name', sortable: true,
		// type: Enums.FieldType.string,
		filterable: true,
		filter: {
			model: Filters.compoundInput
		}
	}, 
	{
		id: 'gender', name: 'Gender', field: 'gender', filterable: true, sortable: true,
		filter: {
			model: Filters.singleSelect,
			collection: [{ value: '', label: '' }, { value: 'male', label: 'male' }, { value: 'female', label: 'female' }]
		}
	},
	{ id: 'company', name: 'Company', field: 'company', filterable: true, sortable: true },
	{ id: 'category_name', name: 'Category', field: 'category.name', filterable: true, sortable: true }
];

export default class Grid1 extends LightningElement {
	isResourceLoaded = false;
	sgb;
	isLoaded = false;
	dataset = []; // load your data through an Apex Controller with @wire
	columns = columns;

	async connectedCallback() {
		if (this.isResourceLoaded) {
			return; // load only once
		}

		this.log('started');
		this.dataset = customers;

		this.log('customers -> ', JSON.stringify(this.dataset));

		await loadResources(this);
		this.initializeGrid();
		this.isResourceLoaded = true;
		this.isLoaded = true;
	}

	initializeGrid() {
		this.log('slickgrid -> ', Slicker);
		this.gridOptions = {
			enableAutoResize: true,
			autoResize: {
				container: '.grid-container',
				minHeight: 250,
				rightPadding: 50,
				bottomPadding: 75,
			},
			checkboxSelector: {
				// you can toggle these 2 properties to show the "select all" checkbox in different location
				hideInFilterHeaderRow: false,
				hideInColumnTitleRow: true
			},
			enableCellNavigation: true,
			enableFiltering: true,
			enableCheckboxSelector: true,
			enableRowSelection: true,
			enablePagination: true, // you could optionally disable the Pagination
			pagination: {
				pageSizes: [10, 20, 50, 100, 500, 50000],
				pageSize: 50,
			},
		
			// or use fixed size
			// gridHeight: 300,
			// gridWidth: 800,
			useSalesforceDefaultGridOptions: true,  // enable this flag to use regular grid options used for SF project


			datasetIdPropertyName: 'id', // default is "Id" (case sensitive)

			/** other options... */
		};

		const container = this.template.querySelector(".user-grid");
		this.sgb = new Slicker.GridBundle(container, this.columns, this.gridOptions, this.dataset);
	}
}
```

grid2.js only different the columns definition which used Filters.multipleSelect for 'gender' column.
```
const columns = [{
		id: 'name', name: 'Name', field: 'name', sortable: true,
		// type: Enums.FieldType.string,
		filterable: true,
		filter: {
			model: Filters.compoundInput
		}
	}, 
	{
		id: 'gender', name: 'Gender', field: 'gender', filterable: true, sortable: true, columnGroup: 'genderGroup',
		filter: {
			model: Filters.multipleSelect,
			collection: [{ value: 'male', label: 'male' }, { value: 'female', label: 'female' }]
		},
        editor: {
          model: Editors.multipleSelect,
          collection: [{ value: 'male', label: 'male' }, { value: 'female', label: 'female' }]
        }
	},
	{ id: 'company', name: 'Company', field: 'company', filterable: true, sortable: true },
	{ id: 'category_name', name: 'Category', field: 'category.name', filterable: true, sortable: true }
];
```

1. And then create the custom tabs with c.grid1 and c.grid2 as 'Grid 1' and 'Grid 2'
2. Hard refresh the browser.
3. Open the 'Grid 1' tab. work as expected.
![grid1-0](https://github.com/ghiscoding/slickgrid-universal/assets/45675425/18717cd0-7a10-46af-a463-c5d5fe05cbed)

4. Open the 'Grid 2' tab, work as expected.
![grid2-0](https://github.com/ghiscoding/slickgrid-universal/assets/45675425/29e9cd12-8c3b-47c5-8d33-00fe65e31686)

5. Browser refresh when 'Grid 2' tab was activated. So 'Grid 2' tab activation remained.
6. Click the 'gender' column filter, 'Grid 2' tab does not display the multiple select checkbox.
7. Click the 'Grid 1' tab and click the 'gender' column filter, radio selector displayed, not checkbox.
![grid1-1](https://github.com/ghiscoding/slickgrid-universal/assets/45675425/721f1242-7e3d-4ef9-ae51-e06cbc8fd881)

8. Browser refresh when 'Grid 1' tab was activated. So 'Grid 1' tab activation remained.
9. 'Grid 1' and 'Grid 2' work as expected.
10. If I try the step 5 again, problem also invoked again.

**Comment by good-ghost** [comment] 2024-03-29 02:23
Just confirm, version 4.6.0 also has same problem.

**Comment by ghiscoding** [comment] 2024-03-29 03:42
dealing with Salesforce problems is just too hard to troubleshoot without having a working demo and in fact I don't work in Salesforce anymore since more than a year and the team upgraded to 3.x a month ago, but not yet to 4.x. You can maybe try an older version of the zip file to be on the version 3.x it should be the same as what we use, try this [version 3 branch](https://github.com/ghiscoding/slickgrid-universal/tree/version3/packages/vanilla-force-bundle/dist-grid-bundle-zip) to get last 3.x zip file. We've been using SlickGrid for the past 2-3 years with thousand of users, it works well. I've been updating the multiple-select-vanilla library recently which is the lib that creates the select and I did some quick testing in Salesforce but just couple of minutes, so it's probably better if you downgrade to version 3.x because at least I know this one works and is used by my coworkers for thousand of users

I'm not sure about that `lwc:dom="manual"` on your div, I don't think you need that and you should probably remove it. 

I remember SlickGrid having problem when Salesforce was in debug or dev mode, I'm not exactly sure of the correct name anymore, been too long.

**Comment by good-ghost** [comment] 2024-03-29 04:58
I just tested with version3 you mentioned.
It also has same problem. --;

**Comment by ghiscoding** [comment] 2024-03-29 05:59
did you use the same html and div class to create the grid? You should try to use unique class name to avoid collision (which might be your problem, I'm not sure). For example `<div class="grid1"></div>`, you displayed `.user-grid` for the 1st grid but I don't know what you used for the 2nd grid, if it's the same then use a different class name if you expect them to be opened in same page but different tab. The thing I don't like about SF is that they never provided any event for when you change Tab, in theory we should always dispose (destroy) the grid before leaving the page. I'm still not exactly sure what your problem is, I don't quite understand it actually. Are you having a problem when going from Grid 1 to Grid 2 and back to Grid 1? The steps are a little confusing but using different class name might help with collision (avoid creating multiple grid on the same target

I'm not sure I can provide much help, it's very hard to troubleshooting anything in Salesforce and I haven't program in it for a while. It works fine for us when we know the limitations of SlickGrid.

**Comment by good-ghost** [comment] 2024-03-29 06:42
OK, Thanks,
I appreciate everything you have done for me.

Let's take a closer look at the code.

**Comment by ghiscoding** [comment] 2024-04-04 15:15
I tested in our Salesforce, we have 2 grids that are in separate tabs and typically the select dropdown are both single select but I converted 1 of the grid to be multiple select like yours and I don't see any problems on my side. So I think the issue is on your side, make sure to use different div class name to target (for example if you use `<div class="grid1">` for both grids then that will give you conflicts at one point or another and is possibly related to your issue). Consider that I tested this, I'll close the issue 

![msedge_RCIQfvsfdk](https://github.com/ghiscoding/slickgrid-universal/assets/643976/54eea08a-a3d3-4f1d-a200-107d9c9e0da7)

**Closed by ghiscoding** 2024-04-04 15:15 UTC
Labels: need repro, more info required
