### ISSUE TITLE
Row Based Edit Plugin

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/slickgrid-universal#1299] opened 2023-12-30 22:10 UTC
### Clear and concise description of the problem

The motivation of this plugin is to create a way for Users to be able to:

* [x] toggle one or multiple rows into editmode
  * [x] when in editmode, a custom css class is applied to the row, along with css vars for styleability (use of `slickGrid?.setCellCssStyles` ?!)
* [x] this is done via a new column
  * [x] which can be positioned by the consumer (https://github.com/zewa666/slickgrid-universal/commit/d4372aae30e774bff4d6ad577779ae93d79fdba2#r135914186)
  * [x] contains an edit, delete, cancel and update button
  * [x] modifications are tracked per row and can be undone using the cancel button
  * [x] the buttons can be styled by the user
  * [x] optionally a prompt message can be defined for cancel and update
* [x] The plugin also makes sure that if CellExternalCopyManager is turned on, pastes are only enabled within editmode cells, respecting any consumer overrides
* [x] A new example is created, along with Cypress tests
* [ ] Documentation is added as a new page to Grid Functionalities with a reference in Editors.md

### Suggested solution

Implement the requirements from above within the common/extensions package using a set of well defined gridOptions.

See https://github.com/ghiscoding/slickgrid-universal/discussions/1290 as related discussion to this issue

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zewa666** [comment] 2024-01-04 21:40
@ghiscoding I'm making some progress on this one. Actually this is a nice opportunity to deep dive a bit more into the Slickgrid-Universal architecture and learn how things are tied together. Next I'll be looking into how to track changes of a row and undo all of them when the cancel button is pressed.

**Comment by ghiscoding** [comment] 2024-01-04 21:51
hey so I'm not sure if this can be helpful or not but while adding full test coverage for SlickDataView, I found this method `syncGridCellCssStyles` which I guess can help to call 1 sync after changing all cell styles? There's a Wiki section in the original SlickGrid project, but I didn't quite understood everything from it [Synchronizing selection & cell CSS styles](https://github.com/6pac/SlickGrid/wiki/DataView#synchronizing-selection--cell-css-styles), if it's helpful then great if not then forget about it haha


https://github.com/ghiscoding/slickgrid-universal/blob/22037ca7918fc4bfb55bb4bf619cd280b564a351/packages/common/src/core/slickDataview.ts#L1552-L1602

**Comment by ghiscoding** [comment] 2024-01-04 22:02
> Next I'll be looking into how to track changes of a row and undo all of them when the cancel button is pressed.

There's 2 undo types in Example 11 and 12
1. undo last edited cell
2. undo all edited cells (except the ones that were already saved)

**Comment by zewa666** [comment] 2024-01-05 05:43
that is perfect, example11, as it seems, contains already pretty much all I need for the editcommand handling and styling

**Comment by zewa666** [comment] 2024-01-05 13:57
Actually Example 30: Composite Editor Modal from angular-slickgrid was even more helpful to achieve the undo feature. So here it is, including the proposed css style additions to row and cell as you mentioned. Looking great so far.

![row-based-edit2](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/5e1db09d-0b10-413b-8062-28e9e4b0dc88)

**Comment by ghiscoding** [comment] 2024-01-05 15:14
well I mean if you're going into this mode that you're adding, the user will nearly 100% of the time want to use single click since he/she already defined that the current row is being edited. Perhaps we can force push `autoEdit` by calling `grid.setOptions({ autoEdit: true })` within the plugin, that is only if the user forget to enable it. I'm not sure about the CSS though.

> as for the save, my idea was to save right after clicking the checkmark, there is a custom callback which the consumer can register to handle the click and do their own backend send stuff.

Well that might differ from user to user, I mean some might want to go with your approach but some might prefer to batch multiple lines and do 1 save at the end, so perhaps a plugin option might be needed? or maybe that's just user config in its own code. The 1 save batch is typically used when user feels their save is a little long, for example some projects in my company uses Salesforce and it's kinda slow so they use batches for some grids which is typically in combo with the Composite Editor.

**Comment by zewa666** [comment] 2024-01-05 15:48
alright, if the user didnt explicitely disable it, which frankly as you said most likely wont happen, we should force push it.

maybe lets clarify what save actually means? I'm not doing anything fancy besides calling an additional callback. I thought saving needs to be handled by the user either way and whether he/she batches calls is up to them. what did you mean instead?

**Comment by ghiscoding** [comment] 2024-01-05 16:08
> maybe lets clarify what save actually means? I'm not doing anything fancy besides calling an additional callback. I thought saving needs to be handled by the user either way and whether he/she batches calls is up to them. what did you mean instead?

ah yeah you're right, it's up to the user, I just wonder if the plugin will keep the choice to the user on how to do the save? Because for example, if you take the Composite Editor plugin that I made, it has its own `onSave` so it is enforcing the user the use of that method, hence removing the user's choice on how to save. In other words, I could ask, how does your plugin works? How does it keep tracks of the changes, is that viewable by the user via a method to read the changes array or is that a closed variable that is handle by the plugin who saves it by itself? In the Composite Editor, I have the `onSave` like I said and the 1st argument is `formValues` which is the values being edited, do you have something similar for changes? 

... if it's all available as any other Edit example via the edit queue like in Example 11-12, then I guess you can forget about all my questions above since that keeps it on the user's side to code so it's his choice on how to implement it. However, I don't see any edit queue in your new [Example 22](https://github.com/zewa666/slickgrid-universal/blob/a13b973593f92cb31f40be1332003573c082cc4a/examples/vite-demo-vanilla-bundle/src/examples/example22.ts), perhaps it because you didn't implement the code yet?

**Comment by zewa666** [comment] 2024-01-05 17:35
so the afterRowUpdated callback gets called with the edited item context. what I'd now do as a consumer would be either directly fire a call against the backend inside the callback, or store these edits in my own updateQueue, create my own save button and send all queue items at once. so the callback is somewhat comparable to the composite editors onSave. Perhaps we should give the callback the same name to make that clearer?

and yes you're right I didnt handle it in my example22 yet. now I get where the confusion came from 😅 so would you like me to make the sample show the simple callback fire away approach or mimick your editqueue thingy?

**Comment by ghiscoding** [comment] 2024-01-05 18:29
You could do the approach you want (edit queue or not) but at least mention it in comments (and probably the docs) that edit queue is also possible (both approach should be documented but demo wise just 1 approach is enough).

> Edit: the later is a very specific way to handle saving. e.g what if one of the entries, assuming its a db in the backend, fails will the rest go through? should a fallback be handled? i felt like this is a lot of second guessing on the users use case and since its handled in user code free to be done the way they like

well on top of `onSave`, I also have the `onError` 😉 You can see the Composite Editor [docs](https://ghiscoding.gitbook.io/slickgrid-universal/grid-functionalities/composite-editor-modal#onerror) for the callback I made available. The way I've done it in the other plugin was to return a Promise in the `onSave` and if the Promise is rejected then it would internally call the `onError`, The typical approach is a Promise but I think I made it work with both a `boolean` or `Promise<boolean>`. There's a few demos in the docs

**Comment by zewa666** [comment] 2024-01-05 19:46
yep I'll make sure to add a note about different handling and also mention the other examples for reference.

CSP is a good hint, I'll fix that with your helper function

with regards to handling onSave and onError. I dont think this applies to this plugin. in the composite editor scenario all changes happen outside and only on success are applied to the dataview. witrh this plugin though changes already happened, hence the name afterRowUpdate. Also I cant think of any specific errors to throw and the options requirements need to be fullfilled otherwise the plugin wont load at all. I could throw an error if not all are fullfilled but the plugin is enabled

**Comment by ghiscoding** [comment] 2024-01-05 19:52
Because you mention potential backend save error, that is what the Promise can reject, it's code from the user not from the plugin that is rejecting the Promise

**Comment by zewa666** [comment] 2024-01-05 21:09
Aaaalrighty so I've updated the feedback so far including:
* [CSP](https://github.com/ghiscoding/slickgrid-universal/commit/b4d451f660d116aba1715f0fcd77fba5f105fdc7)
* [Active bgColor when in Plugins edit mode](https://github.com/ghiscoding/slickgrid-universal/commit/35e70072bc5cc0fe98726e6789b690b07981f43e)
* [Forcing autoEdit (although with a warning) and throw on other missing required gridOptions](https://github.com/ghiscoding/slickgrid-universal/commit/3679da30d0d6b885bea79f3b94653a41e463522c)
* as well as the new documentation for handling the saving and updated Example with a fake fetch (shown in an alert)

![row-based-edit3](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/07b11305-3de1-4eb5-9b69-cede284882bb)

now I think I also understand what you meant with onSave being a promise and requiring a boolean result. So as shown in the GIF, if the backend happens to error out, by resolving with a false or rejecting the promise in the callback you could interupt the save process and keep the edited row still in the editmode ... right?

**Comment by ghiscoding** [comment] 2024-01-05 21:32
This is starting to be looking pretty good 😉 
Maybe 1 thing that I notice, which I'm pretty sure it's on your list of tasks. You used the `.mdi` CSS classes for all the icon, these will have to be changed to be customizable by the user and typically I used the Font-Awesome 4.7 icons by default, I'm not sure that many users are using them anymore but that's typically the default since I created a the lib a few years ago so... 

`if (target.classList.contains('mdi-close') && this._gridService) {`

For example, in the global grid option, I defined the Font-Awesome defaults which the user can override with the ones they want. I think this is better than SASS variables, but if you do want to keep fixed icon class then I would suggest more generic class names 

https://github.com/ghiscoding/slickgrid-universal/blob/ac2a526aec4aeec609cdd0193318bcdfea27face/packages/common/src/global-grid-options.ts#L215-L225

**Comment by zewa666** [comment] 2024-01-05 21:34
yep it's a task on the list (see first post). Great approach with the global-grid-options 👍

**Comment by ghiscoding** [comment] 2024-01-05 21:38
> now I think I also understand what you meant with onSave being a promise and requiring a boolean result. So as shown in the GIF, if the backend happens to error out, by resolving with a false or rejecting the promise in the callback you could interupt the save process and keep the edited row still in the editmode ... right?

For the Composite Editor, the `onError` could be used to block the closing of the modal itself, the errors shows up on top of the form, there is a demo of that in Example 12 if you do a Mass Update with a % Complete below 50% as shown below

![msedge_Q2Dhrl480d](https://github.com/ghiscoding/slickgrid-universal/assets/643976/4fa4b37b-4772-44d8-a6e6-55c99d225248)

If I remember correctly, I also keep Modal open when saving and I show a spinner on the Save button and if there's an error I also show them on the top.

**Comment by ghiscoding** [comment] 2024-01-05 21:45
hey also some small suggestions, some user might want to confirm with a prompt if they really want to proceed with save. I also find your buttons really close together, it might be good to add some paddings and a SASS variable (I already envisioned some fat finger users clicking on the wrong button and complaining about the lib 😆)

**Comment by zewa666** [comment] 2024-01-05 22:48
you can tell my design skills are fantastic right ;) ?

I've pushed an update to address your last comments. I'll check on the promise/boolean thing next.

**Comment by ghiscoding** [comment] 2024-01-06 00:12
> there are also some side-effects, like if you scroll the wrong row stays styled. so I'll have to check the other common features in combo with the plugin as well

I actually had this problem just a few days ago lol, the PR #1307 to fix Example 12 might help with your use case. I left an animated gif showing what the problem was which is probably similar to your problem

**Comment by zewa666** [comment] 2024-01-06 04:44
hmm yeah the bug seems pretty much identical. set row 1 to editmode and edit cell 1. now sort by first column. the same cell stays highlighted but now a different row beneath now is rendered.

I'm just not sure how to use your proposed method as it was leveraged directly in slickgrids core in your case.could you give me a rough idea of where you'd use it?

**Comment by ghiscoding** [comment] 2024-01-06 06:05
Ah sorry I should have mentioned that the sync options are available directly as grid option under the `dataView` option. These options are typically DataView options but since the DataView is instantiated internally, I made these options available in the grid options

```ts
this.gridOptions = {
  syncGridSelection: { 
     preserveHidden: false, 
     preserveHiddenOnSelectionChange: true 
   }, 
}
``` 
but like I said, this should already be the default in the global grid options. I just wanted you to double-check them though.

**Comment by zewa666** [comment] 2024-01-06 10:39
oh ok so if I merge master things might get solved by themselves. cool will try that out

**Comment by zewa666** [comment] 2024-01-06 12:13
so I've now added the prompts for various buttons and renamed the onAfterRowUpdated to onBeforeRowUpdated. This way you can now handle the backend update and return a Promise<boolean> which, if resolves to true, continues to work as usual, and in case of false, keeps the edit mode alive.

![row-based-edit4](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/f2fd9db2-2ec0-4ccf-9647-069f94230b7f)

**Comment by zewa666** [comment] 2024-01-06 12:38
Also I've added now the coop feature with the ExcelCopyBuffer onBeforeCellPaste handler.
![row-based-edit5](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/78e8d7f3-83ef-4167-8494-134fcead2c1d)

**Comment by ghiscoding** [comment] 2024-01-06 16:21
ah nice I had to read the description of your last change in your bullet list to understand, it's pretty cool. This is going to be pretty useful I think. It looks like you're getting closer to the finish line with this feature and you addressed all things I've mentioned, looking pretty good. The only comment I have left is maybe don't use such drastic colors when shipping the feature haha

**Comment by ghiscoding** [comment] 2024-01-06 17:42
> so whats left is the sorting bug. the master merge sadly didnt help. so i'll give it one more try

ah I think I didn't explain well when I talked about the DataView sync earlier, that option has been in place since the early beginning of the project, it's not something recent and I just wanted you to be aware of these options and just compare the values you had loaded. I don't think it will change unless specified by the user.. in short I'd be surprised if it's related.

I can maybe take a look at it once the PR is open. I'm actually not sure if the set cell style is actually supposed to follow the cell or not, I think the itemMetaData will because it's based on the item Id I think but I'm not sure on the cell since it's probably based on the row index which changes when you sort.

**Comment by zewa666** [comment] 2024-01-06 18:08
yeah that was exactly my thinking. subscribe to an event and redraw. the issue though is which events? what about grouping, filtering, ...
so I was hoping there might be something more generic. like currently visible rows in viewport changed, no matter what caused it.

**Comment by ghiscoding** [comment] 2024-01-06 18:18
lol yeah there could be so many events, we might another sync function of some kind. Perhaps we could create a new event to regroup all other events that can cause a reevaluation of the cell styling. So I'm thinking we could maybe add another sync method in the DataView which will subscribe to all necessary events (onSort, onGroup, onPaginationChanged, ....)

along the lines of 
```ts
syncCellStyling(callback) {
  this.eventHandler
    .subscribe(grid.onSort, () => callback)
    .subscribe(this.onGroupCollapsed, () => callback)
}
```
the potential problem that I see is that I have 2 types of Paginations in this project, the local grid Pagination which is handle by the DataView since it has all data and the 2nd Pagination is my own custom one for Backend Service which rather uses the regular PubSub event (basically the latter is not a SlickEvent and is not available in the DataView)... Unless we create this sync in the VanillaGridBundle level (though we will have to replicate it in Angular-Slickgrid, Aurelia-Slickgrid, ....) which has access to everything

**Comment by ghiscoding** [comment] 2024-01-06 18:37
and I think this should be a separate PR... I can take a look at that

**Comment by zewa666** [comment] 2024-01-06 18:50
that would be tremendously helpful. in lots of cases not only cellStyling but imagine custom editors needing to know when they got shifted around. so all what you said but perhaps a more generic name instead of syncCellStyling.

also the unified event subscription you mentioned in another PR, is that perhaps gonna help here?

working on a plugin not only lets you learn the code base (i feel like I've seen tons of new stuff during this journey) but also spawns great additional features.

fully agree this is a PR on itself and I'd gladly ask if you could take that one as it seems you already have a pretty solid idea how to approach it. ping me for a review/testdrive together with this plugin

**Comment by ghiscoding** [comment] 2024-01-06 18:58
> that would be tremendously helpful. in lots of cases not only cellStyling but imagine custom editors needing to know when they got shifted around. so all what you said but perhaps a more generic name instead of syncCellStyling.

what do you suggest?

> also the unified event subscription you mentioned in another PR, is that perhaps gonna help here?

I don't think so, I want to keep using SlickEvent as much as possible internally, the other PR was more of a backup way to subscribe to events because I use 2 types of PubSub events in the project. At one point, I thought of using only SlickEvent but I find it too heavy for simple things like communicating between 2 services (I didn't want to create a SlickEvent just to say that the page changed or the grid state changed, I just wanted to send a message between the 2 services with an existing global pubsub)

> working on a plugin not only lets you learn the code base (i feel like I've seen tons of new stuff during this journey) but also spawns great additional features.

I must say, this is great to have someone else understand the core lib in itself since I'm sure there's still a lot of things that I don't understand myself and having a different pair of eyes like you does help.

**Comment by zewa666** [comment] 2024-01-06 20:16
phew very good question about the name. so the cell styling, editors etc are just symptoms of what is out of sync, the cause itself sounds like your current view on data is no longer in sync with the DataView. Hence perhaps `syncDataView`? or if we keep focus on cells perhaps `syncRenderedCells` as I guess it would really just affect the rendered ones not the whole set.

**Comment by ghiscoding** [comment] 2024-01-06 20:20
gosh... forget about all of that, we already have something in place that does it all lol. Just use `onRowsOrCountChanged` from the DataView and that's it. I tested with Sorting, Grouping, Filtering, Column Reorder, .... it always call the `onRowsOrCountChanged` and it makes sense because that is the event that is used for rerendering the UI anytime something changes. See new PR #1313 that fixes Example 12

As you can see I also need a refresh myself and keep forgetting about amazing features of SlickGrid lol

**Comment by zewa666** [comment] 2024-01-06 22:01
i've seen that one but wouldnt have guessed it from its name but it does make sense afterwards. good catch 👍

**Comment by zewa666** [comment] 2024-01-07 20:07
using the new event I've now fixed that issue as well. So during the next week I'm planning to get the tests and docs done and have the PR created.

**Comment by ghiscoding** [comment] 2024-01-07 21:05
Great to hear, as a side note, I wrote some unit tests for SlickGrid and `setCellCssStyle` with the hash in PR #1314. It might be helpful to write your own tests. I'm getting close to be done with SlickGrid public methods, the last 1-2% of coverage will be though to achieve. Also another side note, JSDOM keeps pushing version that breaks my unit tests which I have to fix every time (23.0 was ok but 23.1 broke and 23.2 broke again with something different it doesn't seem to like querying by `#` id anymore oh well..)

**Comment by zewa666** [comment] 2024-01-10 21:45
quick update, unit tests are done. Boy that took some time to get to 100% :)
next up cypress tests and documentation.

**Comment by ghiscoding** [comment] 2024-01-10 22:39
haha I'm not surprised lol, I've been writing unit tests for the core for the past 2-3 weeks haha

**Closed** 2024-01-18 20:30 UTC
Labels: feature, wip

**Comment by ghiscoding** [comment] 2024-01-18 23:04
@zewa666 some comments I left in new PR #1346 

I looked at your new Example 22 and tweaked the UI a bit and added missing translation unit tests. However while doing that I saw that the "Duration > 40" doesn't always work, it doesn't seem to always detect the error if we use the mouse for the next cell, it seems to work better with Enter key. Sometime the error doesn't show and sometime even fixing the error it doesn't want to go away (see animated gif)

Also, another suggestion. It might be nice to add an extra callback before we go into edit mode, something like `onBeforeEdit: () => void` so that I could use it to clear the notification status message that I added (I mean it shows "success" from previous save, I want to clear that msg when the user click edit again).

![msedge_VSMYI2x0Hi](https://github.com/ghiscoding/slickgrid-universal/assets/643976/b68b15ec-47c9-4f13-a39b-aa3fb6a027e9)

**Comment by zewa666** [comment] 2024-01-19 05:53
all good feedback. according to the issues with save it seems all to be related to not leaving the editor when clicking the save button. is that right. in a typical case where youd either click out of the cell or hit enter this behavior shouldnt be reproducible.

**Comment by ghiscoding** [comment] 2024-01-19 06:07
The main reason I was using the mouse instead of the Enter key is that the Enter goes down on a row that is not the row based one, so instead of clicking Enter then mouse click the next cell, I went straight with just the mouse. I assume that is what most users will want to do. 

That behavior was a little annoying for some which is why someone contributed the `autoCommitEdit: true` which will commit the save right away, but it has a side effect of removing the focus on the cell, so we kind need to click the next cell twice to correctly open, it does however remove the issue for the "> 40". 

You can get more info in the original feature implementation by another user, that was all discussed in Aurelia-Slickgrid in this [issue](https://github.com/ghiscoding/aurelia-slickgrid/issues/82), there's much more info in there

![brave_bQpH47O3Yl](https://github.com/ghiscoding/slickgrid-universal/assets/643976/dec1bf5d-06f7-4a32-a0ed-e01d377c4f73)

**Comment by zewa666** [comment] 2024-01-19 06:46
right but in this case for me it sounds like a known issue that you explicitely have to click out of the cell, perhaps even twice, or use autoCommitEdit.

so the part that the plugin could make sure is before hitting save to actually behind the scenes perform an autocommit even if the autoCommitEdit option is not set.

**Comment by ghiscoding** [comment] 2024-01-19 14:22
yeah that should help, I wasn't sure if you were calling the commit edit or not. Taking a look at the Composite Editor and it is what I do, so it should definitely help

https://github.com/ghiscoding/slickgrid-universal/blob/55e3fc8407e73b0e07170fd74cb7a9907bbaddd5/packages/composite-editor-component/src/slick-composite-editor.component.ts#L958-L967

**Comment by ghiscoding** [comment] 2024-01-20 20:13
@zewa666 the feature is live in Slickgrid-Universal (see [Example 22](https://ghiscoding.github.io/slickgrid-universal/#/example22)) 🎉 

I'll now look at reproducing the feature in the other repos as well and hopefully release by the end of the day 🚀
